{
 "title": "Planspiel Modellfabrik",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"qualityDate\" AS \"time\",\n  \"orderNumber_id\",\n  \"orderPart\"\nFROM database_qualitydata\nWHERE\n  $__timeFilter(\"qualityDate\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Offene Aufträge",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM database_orderdata\nWHERE\n  $__timeFilter(\"orderDate\") and\n  \"orderStatus\"='NEW' OR\n  \"orderStatus\"='PROCESSING'\nORDER BY \"orderStatus\""
    }
   ]
  },
  {
   "title": "Durchlaufzeit Auftrag",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  min(\"timeBeginn\") AS \"time\",\n  max(\"timeEnd\"),\n  \"orderNumber_id\",\n  \"orderPart\"\nFROM database_orderstatus\nWHERE\n  $__timeFilter(\"timeBeginn\")\ngroup by \"orderNumber_id\", \"orderPart\"\norder by \"orderPart\""
    }
   ]
  },
  {
   "title": "Beendete Aufträge",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timeBeginn\" AS \"time\",\n  \"timeEnd\",\n  \"orderNumber_id\",\n  \"orderStation\",\n  \"orderPart\"\nFROM database_orderstatus\nWHERE\n  $__timeFilter(\"timeBeginn\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"orderDate\" AS \"time\",\n  quantity\nFROM database_orderData\nWHERE\n  $__timeFilter(\"orderDate\")\nORDER BY 1"
    }
   ]
  }
 ]
}