# Generated by Django 4.0.6 on 2022-07-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField()),
                ('customerName', models.CharField(max_length=80)),
                ('customerAddress', models.CharField(max_length=80)),
                ('customerPhone', models.CharField(max_length=80)),
                ('customerEmail', models.CharField(max_length=80)),
                ('customerStatus', models.BooleanField()),
                ('customerComment', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameRoundId', models.IntegerField()),
                ('gameRoundStatus', models.BooleanField()),
                ('gameRoundComment', models.CharField(max_length=80)),
                ('gameRoundDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('screw', models.CharField(max_length=10)),
                ('customerId', models.IntegerField()),
                ('orderStatus', models.CharField(max_length=10)),
                ('orderDate', models.DateField()),
                ('orderTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=80)),
                ('orderStation', models.IntegerField()),
                ('orderPart', models.CharField(max_length=10)),
                ('timeBeginn', models.TimeField()),
                ('timeEnd', models.TimeField()),
                ('employee', models.CharField(max_length=80)),
                ('orderStatus', models.CharField(max_length=10)),
                ('orderStatusDescription', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='QualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=80)),
                ('quality', models.IntegerField()),
                ('qualityDate', models.DateField()),
                ('qualityTime', models.TimeField()),
                ('qualityStatus', models.CharField(max_length=10)),
                ('qualityComment', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=80)),
                ('stationId', models.IntegerField()),
                ('stationStatus', models.BooleanField()),
                ('stationLocation', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
