# Generated by Django 4.0.6 on 2022-07-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='customerId',
        ),
        migrations.AddField(
            model_name='orderdata',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.customer'),
            preserve_default=False,
        ),
    ]
