# Generated by Django 4.0.6 on 2022-07-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_orderdata_customerid_orderdata_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.customer'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.orderdata'),
        ),
    ]
