# Generated by Django 4.0.6 on 2022-07-14 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_orderdata_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='orderDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='orderStatus',
            field=models.CharField(default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='orderTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderStation',
            field=models.CharField(choices=[(1, 'Station 1'), (2, 'Station 2'), (3, 'Station 3'), (4, 'Station 4'), (5, 'Station 5'), (6, 'Station 6')], default=1, max_length=2),
        ),
    ]
