# Generated by Django 4.0.6 on 2022-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_orderdata_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='orderDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='orderTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderStation',
            field=models.IntegerField(choices=[(1, 'Station 1'), (2, 'Station 2'), (3, 'Station 3'), (4, 'Station 4'), (5, 'Station 5'), (6, 'Station 6')], default=1),
        ),
    ]
