# Generated by Django 4.0.6 on 2022-07-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_orderstatus_timebeginn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='color',
            field=models.CharField(choices=[('red', 'Rot'), ('yellow', 'Gelb'), ('blue', 'Blau'), ('green', 'Grün')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='orderDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='orderNumber',
            field=models.CharField(default=-1, max_length=80),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='orderStatus',
            field=models.CharField(choices=[('NEW', 'Neu'), ('PROCESSING', 'In Bearbeitung'), ('FINISHED', 'Beendet')], default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='screw',
            field=models.CharField(choices=[('round', 'Rund'), ('hexagon', 'Sechskant')], default='round', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='timeBeginn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='timeEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
