# Generated by Django 4.0.6 on 2022-07-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_orderdata_color_alter_orderdata_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitydata',
            name='orderNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.orderdata'),
        ),
    ]
