# Generated by Django 4.0.6 on 2022-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_qualitydata_orderpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitydata',
            name='qualityTime',
        ),
        migrations.AlterField(
            model_name='qualitydata',
            name='qualityDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
