# Generated by Django 4.0.6 on 2022-07-25 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_qualitydata_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
