# Generated by Django 4.0.6 on 2022-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_orderdata_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitydata',
            name='qualityStatus',
            field=models.CharField(choices=[('NEW', 'Auf dem Weg zur Qualitätskontrolle'), ('PROCESSING', 'In Prüfung'), ('1', 'zurück zu Station 1'), ('2', 'zurück zu Station 2'), ('3', 'zurück zu Station 3'), ('4', 'zurück zu Station 4'), ('5', 'zurück zu Station 5'), ('6', 'zurück zu Station 6'), ('FINISHED', 'Abgeschlossen')], default='NEW', max_length=20),
        ),
    ]
