# Generated by Django 4.0.6 on 2022-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_qualitydata_qualitystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualitydata',
            old_name='quality',
            new_name='failure',
        ),
        migrations.RemoveField(
            model_name='qualitydata',
            name='qualityComment',
        ),
        migrations.RemoveField(
            model_name='qualitydata',
            name='qualityStatus',
        ),
        migrations.AddField(
            model_name='qualitydata',
            name='comment',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='qualitydata',
            name='failureStation',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualitydata',
            name='reworkBeginn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitydata',
            name='reworkEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
