# Generated by Django 4.0.6 on 2022-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_qualitydata_qualitydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitydata',
            name='checkBeginn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitydata',
            name='checkEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
