# Generated by Django 4.0.6 on 2022-07-26 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_qualitydata_failurestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='screw',
        ),
        migrations.AddField(
            model_name='orderdata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(choices=[('red', 'Rot'), ('yellow', 'Gelb'), ('blue', 'Blau'), ('green', 'Grün')], default='red', max_length=10),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='screw',
            field=models.CharField(choices=[('round', 'Rund'), ('hexagon', 'Sechskant')], default='round', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
